name: Enhancement Request
description: Request an enhancement and/or open a science discussion
title: "Put title here!"
body:
  - type: textarea
    id: enhancement-description
    attributes:
      label: What is the feature/what would you like to discuss?
      description: Also tell us, what did you expect to happen?
      placeholder: ex. I'd like to entirely refactor chemistry and here's how.
    validations:
      required: true
  - type: textarea
    id: user-reference
    attributes:
      label: Is there anyone in particular you want to be part of this conversation?
      description: Add the user(s) with @<username>
      placeholder: ex. @confucius
    validations:
      required: false
  - type: dropdown
    id: implemenation
    attributes:
      label: Will you be implementing this enhancement yourself?
      multiple: false
      options:
        - "Yes"
        - "No"
    validations:
      required: false
