name: Other
description: ex. code clean-up, infrastructure updates
title: "Put title here!"
body:
  - type: dropdown
    id: other-type
    attributes:
      label: Issue Type
      multiple: false
      options:
        - Code Clean-up
        - Infrastructure Update
        - Externals Update
        - Documentation Update
        - Other (please describe below)
    validations:
      required: true
  - type: textarea
    id: issue-description
    attributes:
      label: Issue Description
      description: Describe what will change
    validations:
      required: true
  - type: textarea
    id: answer-changing
    attributes:
      label: Will this change answers? (Yes, No, I Don't Know) If yes, why?
      description: If yes, please also add the "answer changing" label
    validations:
      required: true
